#!/usr/bin/env python3
"""Vendor Urbanist and Sora into assets/fonts/ for self-hosting.

The 2026 identity specifies Urbanist (display) and Sora (body). Both are Google
Fonts under the SIL Open Font License, which means -- unlike the Adobe Typekit
dependency this replaces -- they can be self-hosted. That matters: several Tenax
surfaces (notably the on-prem Wazuh dashboard) have no outbound internet access,
and a webfont that silently fails to load takes the brand's typography with it.

Google serves *variable* woff2 files to modern browsers: one file per unicode
subset covering an entire weight range, rather than one file per static weight.
This script asks for those with a current User-Agent, downloads them, and
rewrites the stylesheet to point at the local copies.

Re-run to refresh. Output is deterministic apart from Google's font version
(the ``vNN`` path segment), so a diff after re-running shows upstream changes.

Usage:
    python3 tools/fetch-fonts.py
"""

from __future__ import annotations

import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "fonts"

# A current desktop Chrome UA. Without it Google falls back to serving .ttf,
# which is roughly 3x the transfer size and has no variable-weight support here.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

FAMILIES = [
    # (css family spec, local filename stem, role)
    ("Urbanist:wght@400..800", "urbanist", "display / headings"),
    ("Sora:wght@400..700", "sora", "body / UI"),
]

# Keep the subsets a Tenax UI actually needs. latin-ext covers accented names in
# customer data; dropping the rest keeps the payload small.
KEEP_SUBSETS = {"latin", "latin-ext"}


def fetch(url: str, binary: bool = False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = resp.read()
    return data if binary else data.decode("utf-8")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    blocks: list[str] = []
    downloaded = 0

    for spec, stem, role in FAMILIES:
        css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap")

        # Google emits "/* subset */" before each @font-face; pair them up.
        chunks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
        if not chunks:
            print(f"error: no @font-face rules returned for {spec}", file=sys.stderr)
            return 1

        for subset, rule in chunks:
            if subset not in KEEP_SUBSETS:
                continue
            url_match = re.search(r"url\((https://[^)]+\.woff2)\)", rule)
            if not url_match:
                continue  # non-woff2 fallback; skip
            local = f"{stem}-{subset}.woff2"
            (OUT / local).write_bytes(fetch(url_match.group(1), binary=True))
            downloaded += 1
            rule = rule.replace(url_match.group(0), f"url({local})")
            blocks.append(f"/* {stem} — {role} — {subset} */\n{rule.strip()}")

    header = (
        "/* Tenax Solutions webfonts — self-hosted.\n"
        " *\n"
        " * Urbanist (display) and Sora (body), per the 2026 identity guide.\n"
        " * Both are SIL Open Font License 1.1; the OFL text ships alongside in\n"
        " * this directory. Generated by tools/fetch-fonts.py — do not hand-edit.\n"
        " *\n"
        " * Variable fonts: one file per subset covers the whole weight range, so\n"
        " * any weight in that range is available without an extra request.\n"
        " */\n"
    )
    (OUT / "fonts.css").write_text(header + "\n" + "\n\n".join(blocks) + "\n")

    total = sum(p.stat().st_size for p in OUT.glob("*.woff2"))
    print(f"vendored {downloaded} woff2 files ({total/1024:.0f} KB) + fonts.css into {OUT.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except urllib.error.URLError as exc:
        print(f"error: could not reach Google Fonts ({exc}).", file=sys.stderr)
        raise SystemExit(1)
